apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      initContainers:
      - image: busybox
        name: cleanup
        resources: {}
        volumeMounts:
          - mountPath: /mnt/data
            name: kafka-data
        command:
          - sh
          - -c
          - "rm -rf /mnt/data/lost+found"
      containers:
      - image: containers.instana.io/instana/release/product/kafka:3.2.0_v0.60.0
        name: kafka
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '512m'
            memory: 1Gi
        env:
          - name: ZOOKEEPER_HOST
            value: zookeeper-service
          - name: ADVERTISED_LISTENER
            value: PLAINTEXT://kafka-service.instana-datastores.svc.cluster.local:9092
        ports:
          - containerPort: 9092
        volumeMounts:
          - mountPath: /mnt/log
            name: kafka-logs
          - mountPath: /mnt/data
            name: kafka-data
        securityContext:
          runAsUser: 0
      volumes:
        - name: kafka-logs
          persistentVolumeClaim:
            claimName: kafka-logs
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
status: {}
