---
- name: Add defaults flavour
  include_tasks: process-defaults-flavour-and-config.yaml
  vars:
    this_item_artifact_key: "{{ artifact.key }}"
    this_item_config:  "{{ artifact_item }}"
  loop: "{{ artifact.value }}"
  loop_control:
    loop_var: artifact_item