---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Create Catalog from CASE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: 🛰️  START - AI MANAGER CATALOG - CASE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

- name: Log
  shell: |
    export MESSAGE="Installing IBM CatalogSource - CASE"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true




- name: 📥 Create Catalog Source CASE File
  include_tasks: create-catalog-source-case-file.yml

