---
- name: Get generator to be used for platform {{ cloud_platform }}
  include_tasks: get-generator-dir.yaml

- name: Run generators for {{ GENERATOR_NAME }}
  include_tasks: run-generator.yml
  loop: "{{ GENERATOR_ATTRIBUTES }}"
  loop_control:
    loop_var: OBJECT_ELEMENT_ATTRIBUTES