---
- block:
  - name: Scale service 
    shell: |
      oc patch {{ _current_cp4d_cartridge.CR_Kind }} {{ _current_cp4d_cartridge.CR_Name }}  \
      -n {{ _p_current_cp4d_cluster.project }} \ 
      --type merge \
      -p '{"spec":{"scaleConfig": "{{ _current_cp4d_cartridge.size }}" } }'
  when: (_current_cp4d_cartridge.size | default('')) != ''