---
- name: Insert DPRA options into {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-dpra-install-options.yml
  template:
    src: dpra-install-options.j2
    dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-dpra-install-options.yml"