---
- name: Write replication installations options into {{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-replication-install-options.yml
  copy:
    content: "replication_license_type: {{ _current_cp4d_cartridge.license }}"
    dest: "{{ status_dir }}/cp4d/{{ _p_current_cp4d_cluster.project }}-replication-install-options.yml"