---
- name: "Run the custom resource post-processing scripts"
  include_tasks: "{{ _current_cp4d_cartridge.cr_postprocessing_script }}"
  when: 
  - (_current_cp4d_cartridge.cr_postprocessing_script | default('')) != ''
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'

- name: Scale the service to the size that is specified
  include_tasks: cp4d-set-cartridge-scaling.yml
  when: 
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'

- name: Set cartridge options if specified
  include_tasks: cp4d-set-cartridge-options.yml
  when: 
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'