---
- set_fact:
    _cp4d_admin_password_vault_key_name: "cp4d_admin_{{ _current_cp4d_cluster.project | replace('-','_') }}_{{ _current_cp4d_cluster.openshift_cluster_name | replace('-','_') }}"

- name: Retrieve Cloud Pak for Data admin password for {{ _cp4d_admin_password_vault_key_name }} from the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "{{ _cp4d_admin_password_vault_key_name }}"
    secret_group: "{{ environment_name }}"

- name: Keep admin password
  set_fact:
    _cp4d_login_password: "{{ secret_value }}"

- name: Error if no secret value is returned
  fail: msg="Unable to acquire secret value for {{ _cp4d_admin_password_vault_key_name }} from group {{ environment_name }}"
  when: "secret_value==''"

- name: Get Route to Cloud Pak for Data
  shell: |
    oc --namespace {{ _current_cp4d_cluster.project }} get route -l component=ibm-nginx \
        -o jsonpath="{.items[0].spec.host}"
  register: _cp4d_url

- name: Set profile for cluster {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}
  shell: |
    cpdctl config profile set {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }} \
      --url https://{{ _cp4d_url.stdout }}

- name: Set user for cluster {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}
  shell: |
    cpdctl config user set {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}-admin \
      --username admin --password "{{ _cp4d_login_password }}"

- name: Set context for cluster and user
  shell: |
    cpdctl config context set {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}-context \
      --user {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}-admin \
      --profile {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}

- name: Set current context to {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}-context
  shell: |
    cpdctl config context use {{ _current_cp4d_cluster.openshift_cluster_name }}-{{ _current_cp4d_cluster.project }}-context
