---
- name: Ensure script {{ config_dir }}/{{_current_cp4d_asset.asset_location }}/cp4d-asset.sh is executable
  file:
    path: "{{ config_dir }}/{{_current_cp4d_asset.asset_location }}/cp4d-asset.sh"
    mode: u+rx,g+rx

- name: Run {{ config_dir }}/{{_current_cp4d_asset.asset_location }}/cp4d-asset.sh script if existing, output can be found in {{ status_dir }}/log/{{ _current_cp4d_asset.name }}.log
  shell: |
    {{ config_dir }}/{{_current_cp4d_asset.asset_location }}/cp4d-asset.sh >> {{ status_dir }}/log/{{ _current_cp4d_asset.name }}.log
  args:
    chdir: "{{ config_dir }}/{{_current_cp4d_asset.asset_location }}"
    executable: /bin/bash
  environment:
    CP4D_URL: "https://{{ _cp4d_url.stdout }}"
    CP4D_ADMIN_PASSWORD: "{{ _cp4d_login_password }}"
    CP4D_OCP_PROJECT: "{{ _current_cp4d_cluster.project }}"