---
- name: "Get all cp4d_role definitions"
  set_fact:
    _cp4d_roles: "{{ all_config.cp4d_role | json_query(_roles_current_cluster) | default([]) }}"
  vars:
    _roles_current_cluster: "[? project=='{{ current_cp4d_cluster.project }}' && openshift_cluster_name=='{{ current_cp4d_cluster.openshift_cluster_name }}']"

- name: Adding execute permission to {{ role_path }}/files/create_cp4d_role.sh"
  file: dest={{ role_path }}/files/create_cp4d_role.sh mode=a+x

- name: Adding execute permission to {{ role_path }}/files/delete_cp4d_role.sh"
  file: dest={{ role_path }}/files/delete_cp4d_role.sh mode=a+x

- name: "Loop through each cp4d role CP4D cluster {{ current_cp4d_cluster.project }}"
  include_tasks: handle-custom-role.yml
  loop: "{{ _cp4d_roles | default([]) }}"
  loop_control:
    loop_var: _cp4d_role



