---
- name: Provision DataStage instance from the cartridge specification
  include_tasks: provision_datastage_instance.yml
  loop: "{{ _configured_ds_instances }}"
  loop_control:
    loop_var: _ds_instance