---

- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined

- name: Validate cloud_platform is implemented
  fail: msg="cloud_platform {{ cloud_platform }} is not implemented, current implemented cloud platforms are {{ implemented_cloud_platform_types }} "
  when: "cloud_platform not in implemented_cloud_platform_types"

- name: Show all configuration
  debug:
    var: all_config

- name: Configure NFS servers IBM Cloud VPC
  include_tasks: ibmcloud-nfs-server-vpc-prepare.yaml
  loop: "{{ all_config.nfs_server | default([]) }}"
  loop_control:
    loop_var: current_nfs_server
  when:
  - cloud_platform == 'ibm-cloud'
  - current_nfs_server.infrastructure.type == 'vpc'