---
- name: Provision Cognos instance from the Cognos cartridge specification
  include_tasks: provision_cognos_instance.yml
  loop: "{{ _configured_ca_instances }}"
  loop_control:
    loop_var: _cognos_instance