---
- name: Handling deployment of assets for Cloud Pak for Data cluster
  debug:
    msg: "Handling deploy assets for CP4D cluster {{ current_cp4d_cluster.project }}"

- set_fact:
    _current_openshift_cluster: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ current_cp4d_cluster.openshift_cluster_name }}']

- name: Login to the OpenShift cluster {{ current_cp4d_cluster.openshift_cluster_name }}
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_cp4d_cluster.openshift_cluster_name }}"

- name: Deploy Cloud Pak for Data Assets
  include_role:
    name: cp4d-assets

- name: Configure Cloud Pak for Data Monitors
  include_role:
    name: cp4d-monitors 