apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo-metrics-dif
  namespace: turbonomic
  labels:
      app: turbo-metrics-dif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbo-metrics-dif
  template:
    metadata:
      labels:
        app: turbo-metrics-dif
    spec:
      containers:
      - image: docker.io/niklaushirt/turbo-dif:1.0.1
        imagePullPolicy: IfNotPresent
        name: bastion
        command:
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"
        env:
          - name: RESPTIME_MIN_1
            value : "50"
          - name: RESPTIME_MIN_2
            value : "200"
          - name: RESPTIME_AVG_1
            value : "200"
          - name: RESPTIME_AVG_2
            value : "500"
          - name: RESPTIME_MAX_1
            value : "500"
          - name: RESPTIME_MAX_2
            value : "2000"
          - name: TRANSACTION_MIN_1
            value : "50"
          - name: TRANSACTION_MIN_2
            value : "100"
          - name: TRANSACTION_AVG_1
            value : "100"
          - name: TRANSACTION_AVG_2
            value : "200"
          - name: TRANSACTION_MAX_1
            value : "200"
          - name: TRANSACTION_MAX_2
            value : "300"
---
apiVersion: v1
kind: Service
metadata:
  name: turbo-metrics-dif-service
  namespace: turbonomic
spec:
  selector:
    app: turbo-metrics-dif
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# Source: robot-shop/templates/web-service.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: turbo-metrics-dif
  namespace: turbonomic
spec:
  to:
    kind: Service
    name: turbo-metrics-dif-service
