---
- name: Provision Db2 OLTP instance from the cartridge specification
  include_tasks: provision_db2_instance.yml
  loop: "{{ _configured_db2_instances }}"
  loop_control:
    loop_var: _db2_instance