---
- block:
  - name: Create OpenShift console banner
    template:
      src: console-banner.j2
      dest: "{{ status_dir }}/openshift/{{ _p_openshift_cluster.name }}-console-banner.yaml"

  - name: Create OpenShift console banner
    shell: |
      oc apply -f {{ status_dir }}/openshift/{{ _p_openshift_cluster.name }}-console-banner.yaml
  when: (_p_openshift_cluster.console_banner | default ("")) != ""

- name: Delete console banner if not specified
  shell:
    oc delete ConsoleNotification cpd-console-banner --ignore-not-found
  when: (_p_openshift_cluster.console_banner | default ("")) == ""