---
- name: Format the NFS volume
  include_tasks:
    prepare_xfs_volume.yaml
  vars:
    volume_selector: "{{ nfs_server['infrastructure']['volume_size_gb'] }}G"
    mount_path: /data

- name: Install the NFS server
  include_tasks:
    install_nfs_vpc.yaml
  vars:
    storage_folder: "{{ nfs_server['infrastructure']['storage_folder'] }}"