#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"



# - name: Show Config
#   debug:
#     var: cp4waiops_cluster
- name: 🟡🟡🟡  Show Config File
  debug:
    var: all_config
    verbosity: 2

- name: 🛠️  Get Global Config
  set_fact: global_config={{ all_config.global_config | default([]) }}
- name: 🟡🟡🟡  Show Global Config
  debug:
    var: global_config
    verbosity: 1

# Get OpenShift cluster associated with this CP4WAIOPS project
- name: Get OpenShift definition to use for {{ current_cp4waiops_cluster.project }}
  include_role: 
    name: get-openshift-cluster
  vars:
    _p_openshift_cluster_name: "{{ current_cp4waiops_cluster.openshift_cluster_name | default('') }}"
- name: 🟡🟡🟡  Show Openshift Config
  debug:
    var: _current_openshift_cluster
    verbosity: 1

# Get default storage classes for current OpenShift cluster
- name: Get OpenShift storage classes to use for {{ current_cp4waiops_cluster.project }} and storage name {{ current_cp4waiops_cluster.openshift_storage_name }}
  include_role: 
    name: get-openshift-storage
  vars:
    _p_openshift_cluster_name: "{{ _current_openshift_cluster.name }}"
    _p_openshift_storage_name: "{{ current_cp4waiops_cluster.openshift_storage_name | default('') }}"

# Loop over all instances
- name: MAIN LOOP   🚀 Deploy Cloud Pak for Watson AIOps Assets - Loop over Instances for {{current_cp4waiops_cluster.project}}
  include_role:
    name: cp4waiops-install-modules
  loop: "{{ current_cp4waiops_cluster.instances}}"
  loop_control:
    loop_var: current_cp4waiops_feature

