---
- name: Provision OpenPages instance from the cartridge specification
  include_tasks: provision_openpages_instance.yml
  loop: "{{ _configured_openpages_instances }}"
  loop_control:
    loop_var: _openpages_instance