---
- name: Get {{ _p_openshift_cluster_name }}-kubeconfig secret for OpenShift cluster
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "{{ _p_openshift_cluster_name }}-kubeconfig"
    secret_group: "{{ environment_name }}"
    secret_file: "{{ status_dir }}/openshift/kubeconfig"
  when: 
  - _kubeconfig_cluster != ''

- name: Get generic kubeconfig secret if {{ _p_openshift_cluster_name }}-kubeconfig does not exist
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "kubeconfig"
    secret_group: "{{ environment_name }}"
    secret_file: "{{ status_dir }}/openshift/kubeconfig"
  when: 
  - _kubeconfig_cluster == ''
  - _kubeconfig_generic != ''

- include_tasks: existing-ocp-check-kubeconfig.yml