apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: instana-agent
  namespace: openshift-operators
  labels:
    operators.coreos.com/instana-agent-operator.openshift-operators: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: instana-agent-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace