---
- name: Delete obsolete cartridges
  include_role:
    name: cp4d-cartridge-remove
  vars:
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"

- name: Install selected cartridges for the cluster
  include_role:
    name: cp4d-cartridge-install
  vars:
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"