---
- name: Show logging output
  debug:
    var: _current_logging_output

- name: Generate secret if certificates are defined
  block:
  - name: Retrieve logging output certificate
    include_role: 
      name: vault-get-secret
    vars:
      secret_name: "{{ _current_logging_output.certificates.cert }}"
      secret_group: "{{ environment_name }}"
      secret_file: "{{ status_dir }}/openshift/{{ _current_logging_output.name }}-cert"

  - name: Fail if certificate secret was not found
    fail:
      msg: "Vault secret {{ _current_logging_output.certificates.cert }} was not found or empty"
    when: secret_value==""

  - name: Retrieve logging output key
    include_role: 
      name: vault-get-secret
    vars:
      secret_name: "{{ _current_logging_output.certificates.key }}"
      secret_group: "{{ environment_name }}"
      secret_file: "{{ status_dir }}/openshift/{{ _current_logging_output.name }}-key"

  - name: Fail if key secret was not found
    fail:
      msg: "Vault secret {{ _current_logging_output.certificates.key }} was not found or empty"
    when: secret_value==""

  - name: Retrieve logging output CA bundle
    include_role: 
      name: vault-get-secret
    vars:
      secret_name: "{{ _current_logging_output.certificates.ca }}"
      secret_group: "{{ environment_name }}"
      secret_file: "{{ status_dir }}/openshift/{{ _current_logging_output.name }}-ca"

  - name: Fail if CA bundle secret was not found
    fail:
      msg: "Vault secret {{ _current_logging_output.certificates.ca }} was not found or empty"
    when: secret_value==""

  - name: Create secret for certificates
    shell: |
      oc create secret generic -n openshift-logging {{ _current_logging_output.name }}-secret || true

  - name: Set value for certificate into secret
    shell: |
      oc set data -n openshift-logging secret/{{ _current_logging_output.name }}-secret \
        --from-file=tls.crt={{ status_dir }}/openshift/{{ _current_logging_output.name }}-cert \
        --from-file=tls.key={{ status_dir }}/openshift/{{ _current_logging_output.name }}-key \
        --from-file=ca-bundle.crt={{ status_dir }}/openshift/{{ _current_logging_output.name }}-ca 
  when: _current_logging_output.certificates is defined