---
- name: Provision EnterpriseDB instance from the cartridge specification
  include_tasks: provision-cpd-edb-instance.yml
  loop: "{{ _configured_cpd_edb_instances }}"
  loop_control:
    loop_var: _cpd_edb_instance