kind: Service
apiVersion: v1
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: clickhouse-8123
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: clickhouse-9000
  type: ClusterIP