---
- name: Provision Analytics Engine instance from the cartridge specification
  include_tasks: provision_analyticsengine_instance.yml
  loop: "{{ _configured_ae_instances }}"
  loop_control:
    loop_var: _ae_instance