kind: Namespace
apiVersion: v1
metadata:
  name: instana-datastores
  labels:
    kubernetes.io/metadata.name: instana-datastores
  annotations:
    openshift.io/node-selector: role=instana
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"Key": "dedicated", "Operator": "Equal", "Value": "instana","Effect":"NoSchedule"}]
spec: {}