---

- name: Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - VAULT_PASSWORD is defined

- name: Validate if valid login session is available
  shell: |
    vault kv list \
      -address {{ hashicorp_vault_address }} \
      /secret
  ignore_errors: yes
  no_log: true
  register: hashicorp_vault_list_result
  failed_when: False

- name: Determine if Hashicorp Vault login can be skipped
  debug:
    msg: "Login to {{ hashicorp_vault_address }} already available, skip login..."
  when: "hashicorp_vault_list_result.rc == 0"

- name: Login to Hashicorp Vault if vault list failed
  block:

    - name: Login to vault {{ hashicorp_vault_address }} using token
      shell: |
         vault login \
         -address {{ hashicorp_vault_address }} \
           {{ VAULT_PASSWORD }} 
      register: hashicorp_vault_login_result
      failed_when: "not hashicorp_vault_login_result.rc == 0"

    - name: Test connection to vault
      shell: |
        vault kv list \
          -address {{ hashicorp_vault_address }} \
          /secret
      register: hashicorp_vault_list_after_login_result
      failed_when: "not hashicorp_vault_list_after_login_result.rc == 0"

  when: "not hashicorp_vault_list_result.rc == 0"

- name: Successfully logged into Hashicorp Vault using API key
  debug:
    msg: "Successfully logged into {{ hashicorp_vault_address }} with api-key"