---
- set_fact:
    _configured_cartridge: "{{ _all_cartridges | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ _current_cartridge_cr.name }}']

- debug:
    msg: "{{ _configured_cartridge }}"

- name: Check if cartridge {{ _current_cartridge_cr.name }} is currently installed
  shell: |
    oc get {{ _current_cartridge_cr.cr_cr }} {{ _current_cartridge_cr.cr_name }} --namespace {{ _p_current_cp4d_cluster.project }}
  failed_when: False
  register: _cartridge_installed

- include_tasks: cp4d-remove-cr.yml
  when:
  - _cartridge_installed.rc == 0
  - _surviving_cartridges | selectattr('CR_Kind','equalto',(_configured_cartridge.CR_Kind | default(''))) | list | count == 0
  - _configured_cartridge == {} or ((_configured_cartridge.state | default('installed')) == 'removed' )