---
- include_role:
    name: cp4d-variables

- name: Remove obsolete cartridges from CP4D cluster {{ _p_current_cp4d_cluster.project }}
  debug:
    msg: "Remove obsolete cartridges from CP4D cluster {{ _p_current_cp4d_cluster.project }}"

- name: Check which obsolete cartridges are still installed
  include_tasks: cp4d-check-remove-cr.yml
  loop: "{{ _all_cartridges }}"
  loop_control:
    loop_var: _current_cartridge_cr
  when:
  - (_current_cartridge_cr.cr_cr | default('')) != ''
  - not (_current_cartridge_cr.embedded | default(False) | bool)
  - not (_current_cartridge_cr.cr_internal | default(False) | bool)
  - not _current_cartridge_cr.name in ['cpfs','cp-foundation','cpd_platform','lite','scheduler']