---
- include_tasks: aws-rosa-configure-ocs.yml
  when: current_openshift_cluster.infrastructure.type == 'rosa'

- include_tasks: aws-ipi-configure-ocs.yml
  when: current_openshift_cluster.infrastructure.type == 'self-managed'