---
- name: Get storage classes from cluster
  shell:
    oc get sc -o jsonpath='{.items[*].metadata.name}'
  register: _openshift_storage_classes

- set_fact:
    _storage_type: 'pwx'
  when: (_openshift_storage_classes.stdout | regex_search('px-db', multiline=True)) != None

- name: Check if Portworx has been installed on the cluster
  fail:
    msg: "Portworx is not installed on the cluster"
  when:
  - (_openshift_storage_classes.stdout | regex_search('px-db', multiline=True)) == None
  - (_openshift_storage_classes.stdout | regex_search('px-csi-db', multiline=True)) == None

- name: Create Portworx non-CSI storage classes for CP4D
  shell:
    /opt/ansible/bin/px-sc.sh
  failed_when: False
  when:
  - (_openshift_storage_classes.stdout | regex_search('px-csi-db', multiline=True)) == None

- name: Create Portworx CSI storage classes for CP4D
  shell:
    /opt/ansible/bin/px-sc-csi.sh
  failed_when: False
  when:
  - (_openshift_storage_classes.stdout | regex_search('px-csi-db', multiline=True)) != None