---
- name: Provision Data Virtualization instance from the DV cartridge specification
  include_tasks: provision_dv_instance.yml
  loop: "{{ _configured_dv_instances }}"
  loop_control:
    loop_var: _dv_instance