---
- include_tasks: destroy-infra-ibm-cloud.yml
  when: cloud_platform == 'ibm-cloud'

- include_tasks: destroy-infra-aws.yml
  when: cloud_platform == 'aws'

- include_tasks: destroy-infra-azure.yml
  when: cloud_platform == 'azure'