---
- set_fact:
    ocp_storage_class_file: "{{ current_openshift_storage.ocp_storage_class_file | default('managed-nfs-storage') }}"
    ocp_storage_class_block: "{{ current_openshift_storage.ocp_storage_class_block | default('managed-nfs-storage') }}"

- name: Check if file storage class {{ ocp_storage_class_file }} exists
  shell:
    oc get sc {{ ocp_storage_class_file }}

- name: Check if block storage class {{ ocp_storage_class_block }} exists
  shell:
    oc get sc {{ ocp_storage_class_block }}
  when: ocp_storage_class_block != ocp_storage_class_file
