
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patches
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: 🩹 PATCH - Restart Demo UI
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    if [ "${WAIOPS_NAMESPACE}" != "" ]; then
      oc delete pod $(oc get po -n $WAIOPS_NAMESPACE-demo-ui|grep demo-ui|awk '{print$1}') -n cp4waiops-demo-ui --ignore-not-found
    fi
  ignore_errors: true


