---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - secret_group is defined
      - secret_name is defined

- name: Check that vault file {{ secret_group }} exists
  stat:
    path: "{{ status_dir }}/vault/{{ secret_group }}"
  register: vault_file_details

- name: Fail if the secret file was not found
  fail:
    msg: "File {{ status_dir }}/vault/{{ secret_group }} does not exist"
  when: not vault_file_details.stat.exists

- name: Add or replace secret in file {{ status_dir }}/vault/{{ secret_group }}
  lineinfile:
    path: "{{ status_dir }}/vault/{{ secret_group }}"
    regexp: "^{{ secret_name }}"
    state: absent

- name: Successfully deleted secret
  debug:
    msg: "Secret {{ secret_group }}/{{ secret_name }} deleted..."