---
- name: Delete Secret from Vault Hashicorp
  block:
    - name: Validate mandatory variables are defined for Hashicorp Vault
      assert:
        that:
          - vault_secret_path is defined

    - set_fact:
        _secret_name: "{{ secret_name }}"

    - set_fact:
        _hashicorp_secret_name_path: "{{ _secret_name }}"
      when: _secret_name is search("/")

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ secret_group}}/{{ _secret_name }}"
      when: 
      - (vault_secret_path_append_group | default(True) | bool)
      - not _secret_name is search("/")

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ _secret_name }}"
      when: 
      - not (vault_secret_path_append_group | default(True) | bool)
      - not _secret_name is search("/")

    - name: Delete Secret Hashicorp vault (API Key), path {{ _hashicorp_secret_name_path }}
      include_tasks: delete-secret-hashicorp-api-key.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'api-key'

    - name: Delete Secret Hashicorp vault (Certificate), path {{ _hashicorp_secret_name_path }}
      include_tasks: delete-secret-hashicorp-certificate.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'certificate'      
  when: "vault_type == 'hashicorp-vault'"

- name: Delete Secret from Vault IBM Cloud
  block:
    - name: Delete secret from Vault IBMCloud
      include_tasks: delete-secret-ibmcloud.yml
      vars:
        ibmcloud_vault_address: "{{ vault_url }}"
        ibm_cloud_secret_name: "{{ secret_name }}"
  when: "vault_type == 'ibmcloud-vault'"

- name: Delete Secret from Vault file
  block:
    - name: Get secret in Vault file
      include_tasks: delete-secret-file.yml
  when: "vault_type == 'file-vault'"

- name: Secret {{ secret_group }}/{{ secret_name }} was deleted
  debug:
    msg: ""
  vars:
    ansible_callback_diy_runner_on_ok_msg: |+2
      Secret {{ secret_group }}/{{ secret_name }} was deleted