---
- name: Delete secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - VAULT_CERT_CA_FILE is defined
      - VAULT_CERT_KEY_FILE is defined
      - VAULT_CERT_CERT_FILE is defined
      - hashicorp_secret_name_path is defined

- name: Delete the secret
  shell: |
    vault kv delete \
      -ca-cert={{ VAULT_CERT_CA_FILE }} \
      -client-cert={{ VAULT_CERT_CERT_FILE }} \
      -client-key={{ VAULT_CERT_KEY_FILE }} \
      -address={{ hashicorp_vault_address }} \ 
      {{ hashicorp_secret_name_path }}

- name: Successfully deleted secret
  debug:
    msg: "Secret {{ hashicorp_secret_name_path }} deleted..."