---
- name: Delete secret Validate mandatory variables are defined
  assert:
    that:
      - secret_name is defined
      - ibmcloud_vault_address is defined
      - ibm_vault_token_content is defined

- name: Get the secret id if the secret exists
  include_role:
    name: vault-has-secret

- name: Delete secret value
  block:
    - name: Delete Secret {{ secret_name }} from group {{ secret_group }}
      uri:
        url: "{{ ibmcloud_vault_address }}/v1/ibmcloud/arbitrary/secrets/groups/{{ ibm_cloud_secret_group_id }}/{{ secret_id }}"
        headers:
          X-Vault-Token: "{{ ibm_vault_token_content.auth.client_token }}"
          Accept: "application/json"
        status_code: 200
        method: DELETE
      register: response_deleteSecret

    - name: Show response of deleting secret
      debug:
        msg: "{{ response_deleteSecret }}"

    - name: Successfully deleted secret
      debug:
       msg: "Secret {{ secret_name }} from group {{ ibm_cloud_secret_group_id }} has been deleted"
  when: "has_secret == true"      

