---
- name: Delete secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - hashicorp_secret_name_path is defined

- name: Delete secret
  shell: |
    vault kv delete \
      -address={{ hashicorp_vault_address }} \ 
      {{ hashicorp_secret_name_path }}

- name: Successfully deleted secret
  debug:
    msg: "Secret {{ hashicorp_secret_name_path }} deleted..."