- name: 🛰️  START - RUN SNOW TRAINING
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"




- name: Log
  shell: |
    export MESSAGE="Run SNOW Training"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true



- name: 🚀 TRAINING RUN - RUN TRAINING SNOW
  shell: |
    set -x
    
    echo "  ***************************************************************************************************************************************************"
    echo "   🛠️   Run Analysis: Change Risk"
    export FILE_NAME=run-analysis-CR.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh


    echo "  ***************************************************************************************************************************************************"
    echo "   🛠️   Run Analysis: Similar Incidents"
    export FILE_NAME=run-analysis-SI.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh

  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash


- name: 🟣 TRAINING RUN - RESULT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1

