---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - secret_group is defined
      - secret_name is defined

- name: Create directory {{ status_dir }}/vault if not existent
  file:
    path: "{{ status_dir }}/vault"
    state: directory

- name: Create file-vault file {{ status_dir }}/vault/{{ secret_group }} if not existent
  file:
    path: "{{ status_dir }}/vault/{{ secret_group }}"
    state: touch

- name: Show command to retrieve secret from file
  debug:
    msg: "{{ lookup('template','get-secret-from-file.j2') }}"

- set_fact:
    _secret_value_b64: "{{ lookup('ansible.builtin.pipe', lookup('template','get-secret-from-file.j2')) }}"

- set_fact:
    has_secret: false
  when: (_secret_value_b64 | length) == 0

- set_fact:
    has_secret: true
  when: (_secret_value_b64 | length) != 0

- name: Result of determining if secret exists
  debug:
    msg: "Secret {{ secret_name }} lookup resulted in: {{ has_secret }}"