---
- name: Create secret Validate mandatory variables are defined
  assert:
    that:
      - ibm_cloud_secret_name is defined
      - ibmcloud_vault_address is defined
      - ibm_vault_token_content is defined

- name: Get the Cloud vault group id
  include_role: 
     name: vault-group

- name: Validate if the secret {{ secret_name }} is available
  uri:
    url: "{{ ibmcloud_vault_address }}/v1/ibmcloud/arbitrary/secrets/groups/{{ ibm_cloud_secret_group_id }}"
    headers:
      X-Vault-Token: "{{ ibm_vault_token_content.auth.client_token }}"
      Accept: "application/json"    
    status_code: 200
  register: response_getSecret

- set_fact:
    response_getSecret_query_result: "{{ response_getSecret.json.data.secrets | json_query(query_secret) }}"
  vars:
    query_secret: "[?name=='{{ secret_name }}']"

- set_fact:
    has_secret: false
  when: "response_getSecret_query_result|length == 0"

- set_fact:
    has_secret: true
    secret_id: "{{ response_getSecret_query_result[0].id }}"
  when: "response_getSecret_query_result|length == 1"

- name: Result of checking if secret exists
  debug:
    msg: "Secret {{ secret_name }} lookup resulted in: {{ has_secret }}"