---
- name: Validate mandatory variables for upstream DNS servers are defined
  assert:
    that:
      - _p_upstream_dns is defined

- shell: |
    echo '{{ lookup('template','dns.j2',convert_data=False) | string }}'

- name: Patch the DNS custom resource
  shell:
    oc patch dns.operator/default \
      --type=json \
      -p '[{"op":"replace","path":"/spec/servers","value":{{ lookup('template','dns.j2',convert_data=False) }} }]' -o yaml