---
- name: Create secret Validate mandatory variables are defined
  assert:
    that:
      - ibm_cloud_secret_name is defined
      - ibmcloud_vault_address is defined
      - ibm_vault_token_content is defined    
      - ibm_vault_secret_payload is defined

- name: Fail if a secret field was specified for a vault other than Hashicorp
  fail:
    msg: "Secret name {{ secret_name }} can only have a secret field specification for Hashicorp Vault"
  when: secret_name is search(",")

- name: Validate if the secret already exists
  include_role: 
     name: vault-has-secret

- name: Delete secret {{ ibm_cloud_secret_name }} in group {{ ibm_cloud_secret_group_id }} if it already exists
  include_role:
    name: vault-delete-secret
  when: "has_secret == true"

- name: Create new secret {{ secret_name }} in group {{ secret_group }}
  uri:
    url: "{{ ibmcloud_vault_address }}/v1/ibmcloud/arbitrary/secrets/groups/{{ ibm_cloud_secret_group_id }}"
    headers:
      X-Vault-Token: "{{ ibm_vault_token_content.auth.client_token }}"
      Accept: "application/json"
      Content-Type: "application/json"    
    method: POST
    body_format: json
    body:
      name: "{{ ibm_cloud_secret_name }}"
      payload: "{{ ibm_vault_secret_payload }}"
    status_code: 200
  register: response_createSecret

- name: Successfully created IBM Cloud Vault secret
  debug:
    msg: "Secret {{ secret_name }} successfully created on IBMCloud vault"