---
- name: Create secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - hashicorp_secret_name_path is defined
      - hashicorp_secret_field is defined

- set_fact:
    _vault_secret_base64: True
  when: (vault_secret_base64 | default(True) | bool)

- set_fact:
    _vault_secret_base64: False
  when: not (vault_secret_base64 | default(True) | bool)

- name: Hashicorp Vault secrets will be written in base64 encoding
  debug:
    msg: "Hashicorp Vault secrets will be written in base64 encoding: {{ _vault_secret_base64 }}"

- name: Set secret inside vault via value
  block:
  - name: Set secret value in plain text
    shell: |
      vault kv put \
        -address={{ hashicorp_vault_address }} \ 
        {{ hashicorp_secret_name_path }} \
        {{ hashicorp_secret_field }}="{{ hashicorp_secret_payload }}"
    register: hashicorp_vault_create_result
    when: not _vault_secret_base64

  - name: Set secret value in base64 encoding
    shell: |
      vault kv put \
        -address={{ hashicorp_vault_address }} \ 
        {{ hashicorp_secret_name_path }} \
        {{ hashicorp_secret_field }}="{{ hashicorp_secret_payload | b64encode }}"
    register: hashicorp_vault_create_result
    when: _vault_secret_base64
  when: (hashicorp_secret_file | default("") == "")

- name: Set secret value via file in plain text
  shell: |
    vault kv put \
      -address={{ hashicorp_vault_address }} \ 
      {{ hashicorp_secret_name_path }} \
      {{ hashicorp_secret_field }}=@{{ hashicorp_secret_file }}
  register: hashicorp_vault_create_result
  when: 
    - not _vault_secret_base64
    - (hashicorp_secret_file | default("") != "")

- name: Set the secret inside vault via file in base64
  block: 
  - name: Create temporary file for base64 content
    tempfile:
      state: file
    register: _vault_secret_base64_file

  - name: Write secret in base64 to temporary file
    shell: |
      cat {{ hashicorp_secret_file }} | base64 -w 0 > {{ _vault_secret_base64_file.path }}

  - name: Set secret value via file in base64
    shell: |
      vault kv put \
        -address={{ hashicorp_vault_address }} \ 
        {{ hashicorp_secret_name_path }} \
        {{ hashicorp_secret_field }}=@{{ _vault_secret_base64_file.path }}
    register: hashicorp_vault_create_result

  when: 
    - (hashicorp_secret_file | default("") != "")
    - _vault_secret_base64

- name: Successfully created secret in Hashicorp Vault
  debug:
    msg: "Secret {{ hashicorp_secret_name_path }} field {{ hashicorp_secret_field }} successfully created on Hashicorp vault"