---
- set_fact:
    secret_payload: "{{ secret_value }}"
  when: not secret_value is match("@.*")

- set_fact:
    secret_file: "{{ secret_value[1:] }}"
  when: secret_value is match("@.*")

- include_tasks: create-secret.yml