- name: Validate mandatory variables are defined for Hashicorp Vault
  assert:
    that:
      - vault_secret_path is defined
      - vault_secret_field is defined

- set_fact:
    _secret_field: "{{ vault_secret_field }}"

- set_fact:
    _secret_field: "{{ secret_name.split(',')[1] }}"
  when: secret_name is search(",")

- set_fact:
    _secret_name: "{{ secret_name.split(',')[0] }}"

- set_fact:
    _hashicorp_secret_name_path: "{{ _secret_name }}"
  when: _secret_name is search("/")

- set_fact:
    _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ secret_group}}/{{ _secret_name }}"
  when: 
  - (vault_secret_path_append_group | default(True) | bool)
  - not _secret_name is search("/")

- set_fact:
    _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ _secret_name }}"
  when: 
  - not (vault_secret_path_append_group | default(True) | bool)
  - not _secret_name is search("/")

- include_tasks: create-secret-hashicorp-api-key.yml
  vars:
    hashicorp_vault_address: "{{ vault_url }}"
    hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
    hashicorp_secret_field: "{{ _secret_field }}"
    hashicorp_secret_payload: "{{ secret_payload }}"
  when: 
  - vault_authentication_type == 'api-key'
  - (secret_file | default("") == "")

- include_tasks: create-secret-hashicorp-api-key.yml
  vars:
    hashicorp_vault_address: "{{ vault_url }}"
    hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
    hashicorp_secret_field: "{{ _secret_field }}"
    hashicorp_secret_file: "{{ secret_file }}"
  when: 
  - vault_authentication_type == 'api-key'
  - (secret_file | default("") != "")

- include_tasks: create-secret-hashicorp-certificate.yml
  vars:
    hashicorp_vault_address: "{{ vault_url }}"
    hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
    hashicorp_secret_field: "{{ _secret_field }}"
    hashicorp_secret_payload: "{{ secret_payload }}"
  when:
  - vault_authentication_type == 'certificate'
  - (secret_file | default("") == "")

- include_tasks: create-secret-hashicorp-certificate.yml
  vars:
    hashicorp_vault_address: "{{ vault_url }}"
    hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
    hashicorp_secret_field: "{{ _secret_field }}"
    hashicorp_secret_file: "{{ secret_file }}"
  when:
  - vault_authentication_type == 'certificate'
  - (secret_file | default("") != "")
