- name: Validate mandatory variables are defined
  assert:
    that:
      - _p_vault_secrets is defined or secret_name is defined
      - secret_group is defined

- debug:
    var: _p_vault_secrets

- include_tasks: create-secrets.yml
  vars:
    secret_name: "{{ item.key }}"
    secret_value: "{{ item.value }}"
  with_dict: "{{ _p_vault_secrets }}"
  when: _p_vault_secrets is defined

- include_tasks: create-secret.yml
  when: _p_vault_secrets is not defined