---
- name: Delete the user-workload-monitoring-config configmap
  shell: |
    oc delete cm -n openshift-user-workload-monitoring user-workload-monitoring-config --ignore-not-found

- name: Delete the cluster-monitoring-config configmap
  shell: |
    oc delete cm -n openshift-monitoring cluster-monitoring-config --ignore-not-found
