---
- name: Create secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - VAULT_CERT_CA_FILE is defined
      - VAULT_CERT_KEY_FILE is defined
      - VAULT_CERT_CERT_FILE is defined
      - hashicorp_secret_name_path is defined

- name: Get the list of secrets
  shell: |
    vault kv list \
      -ca-cert={{ VAULT_CERT_CA_FILE }} \
      -client-cert={{ VAULT_CERT_CERT_FILE }} \
      -client-key={{ VAULT_CERT_KEY_FILE }} \
      -address={{ hashicorp_vault_address }} \
      -format=json \ 
      {{ hashicorp_secret_name_path }}
  register: hashicorp_vault_list_secrets_result

- name: Result of listing secrets
  debug:
    var: hashicorp_vault_list_secrets_result

- set_fact:
    secret_list: "{{ hashicorp_vault_list_secrets_result.stdout | from_json | list }}"
