---

- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - ibmcloud_vault_address is defined
      - ibm_vault_token_content is defined

- name: Get the Cloud vault group id
  include_role: 
     name: vault-group

- name: List secrets
  block:
    - name: List secrets from group {{ secret_group }}
      uri:
        url: "{{ ibmcloud_vault_address }}/v1/ibmcloud/arbitrary/secrets/groups/{{ ibm_cloud_secret_group_id }}"
        headers:
          X-Vault-Token: "{{ ibm_vault_token_content.auth.client_token }}"
          Accept: "application/json"
        status_code: 200
      register: response_listSecret

    - set_fact:
        secret_list: "{{ response_listSecret.json.data.secrets | json_query(get_secrets) | list }}"
      vars:
        get_secrets: "[*].name"


