---

- name: Get Secret from Vault Hashicorp
  block:
    - name: Validate mandatory variables are defined for Hashicorp Vault
      assert:
        that:
          - vault_secret_path is defined
          - secret_group is defined

    - set_fact:
        _secret_name: "{{ secret_name | default('') }}"

    - set_fact:
        _hashicorp_secret_name_path: "{{ _secret_name }}"
      when: _secret_name is search("/")

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}/{{ secret_group}}"
      when: 
      - (vault_secret_path_append_group | default(True) | bool)
      - not _secret_name is search("/")

    - set_fact:
        _hashicorp_secret_name_path: "{{ vault_secret_path }}"
      when: 
      - not (vault_secret_path_append_group | default(True) | bool)
      - not _secret_name is search("/")

    - name: List secrets in Hashicorp vault (API Key), path {{ _hashicorp_secret_name_path }}
      include_tasks: list-secrets-hashicorp-api-key.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'api-key'

    - name: List secrets in Hashicorp vault (Certificate), path {{ _hashicorp_secret_name_path }}
      include_tasks: list-secrets-hashicorp-certificate.yml
      vars:
        hashicorp_vault_address: "{{ vault_url }}"
        hashicorp_secret_name_path: "{{ _hashicorp_secret_name_path }}"
      when: vault_authentication_type == 'certificate'      
  when: "vault_type == 'hashicorp-vault'"

- name: List secrets from Vault IBM Cloud
  include_tasks: list-secrets-ibmcloud.yml
  vars:
    ibmcloud_vault_address: "{{ vault_url }}"
  when: "vault_type == 'ibmcloud-vault'"

- name: List secrets from Vault file
  include_tasks: list-secrets-file.yml
  when: "vault_type == 'file-vault'"

- name: Secrets in group {{ secret_group }}
  debug:
    var: secret_list
  vars:
    ansible_callback_diy_runner_on_ok_msg: |+2
      Secret list for group {{ secret_group }}: 
      {{ ansible_callback_diy.result.output.secret_list | to_nice_yaml }}
