---
- name: Process all elements in object list {{ _all_config_item.key }}
  include_tasks: pre-process-object-list-element.yaml
  loop: "{{ _all_config_item.value }}"
  loop_control:
    index_var: object_element_index
    loop_var: object_element