---
- import_playbook: playbook-env-apply-10-validate.yml
- import_playbook: playbook-env-apply-20-prepare.yml
- import_playbook: playbook-env-apply-60-configure-cloud-pak.yml
- import_playbook: playbook-env-apply-70-deploy-assets.yml
- import_playbook: playbook-env-apply-80-smoke-tests.yml

