---
- name: 80 - Smoke tests
  hosts: localhost
  connection: local
  become: True
  gather_facts: False
  environment:
    KUBECONFIG: "{{ status_dir }}/openshift/kubeconfig"

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""
    ansible_callback_diy_playbook_on_include_msg: ""

  tasks:
  - name: Store all configuration into the vault for later comparison
    include_role:
      name: vault-set-secret
    vars:
      secret_name: "{{ environment_name }}-all-config"
      secret_description: "All configuration"
      secret_payload: "{{ all_config }}"
      secret_group: "{{ environment_name }}"

  - name: Cloud Pak for Business Automation smoke tests
    include_role:
      name: cp4ba-cluster-smoke-tests
    loop: "{{ all_config.cp4ba | default([]) }}"
    loop_control:
      loop_var: current_cp4ba_cluster

  - name: Cloud Pak for Data smoke tests
    include_role:
      name: cp4d-cluster-smoke-tests
    loop: "{{ all_config.cp4d | default([]) }}"
    loop_control:
      loop_var: current_cp4d_cluster

  - name: Cloud Pak for Integration smoke tests
    include_role:
      name: cp4i-cluster-smoke-tests
    loop: "{{ all_config.cp4i | default([]) }}"
    loop_control:
      loop_var: current_cp4i_cluster