---

- name: Prepare yaml file for catalog sources
  template:
    src: cp4i-catalog-sources.j2
    dest: "{{ status_dir }}/cp4i/cp4i-catalog-sources.yml"

- name: "Install CatalogSources from {{ status_dir }}/cp4di/cp4i-catalog-sources.yml"
  shell: |
    oc apply -f {{ status_dir }}/cp4i/cp4i-catalog-sources.yml
