# Example of the functionality call
# Based on https://www.ibm.com/docs/en/cpfs?topic=apis-oidc-registration#get2 (Get access token by using username and password)
#
# - name: Get IAM token
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: iam-token
#   vars:
#     common_cpfs_project: _cpfs_project
#     common_client_id: _client_id
#     common_client_secret: _client_secret
#     common_output_to_var: "iam_token"

- name: Get OCP Apps domain
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"

- name: Get IAM access token
  ansible.builtin.uri:
    url: "https://cp-console-{{ common_cpfs_project }}.{{ apps_endpoint_domain }}/idprovider/v1/auth/identitytoken"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded;charset=UTF-8
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
      client_id: "{{ common_client_id }}"
      client_secret: "{{ common_client_secret }}"
      scope: openid
    validate_certs: false
    status_code: 200
  register: token_response

- name: Set apps endpoint
  ansible.builtin.set_fact:
    "{{ common_output_to_var }}": "{{ token_response | json_query('json.access_token') }}"
