# Example of the functionality call
#
# - name: Wait for StatefulSet to be available
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: wait-statefulset-available
#   vars:
#     common_resource_name: resource_name
#     common_resource_namespace: _resource_namespace
#     common_retries: retries
#     common_delay: delay

- name: Wait on api version apps/v1, kind StatefulSet, name '{{ common_resource_name }}'
    in namespace '{{ common_resource_namespace }}' to be available
    with '{{ common_retries }}' retries with '{{ common_delay }}' seconds delay each (total of '{{ common_retries * common_delay / 60 }}' minutes)
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ common_resource_name }}"
    namespace: "{{ common_resource_namespace }}"
  register: common_resource_condition
  retries: "{{ common_retries }}"
  delay: "{{ common_delay }}"
  until: common_resource_condition.resources is defined and
    common_resource_condition.resources[0].status.currentReplicas is defined and
    common_resource_condition.resources[0].status.readyReplicas is defined and
    (common_resource_condition.resources[0].status.readyReplicas >= 1)
