---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - hashicorp_secret_name_path is defined
      - hashicorp_secret_field is defined

- set_fact:
    _vault_secret_base64: True
  when: (_vault_secret_base64 | default(True) | bool)

- set_fact:
    _vault_secret_base64: False
  when: not (vault_secret_base64 | default(True) | bool)

- name: Hashicorp Vault secrets will be retrieved using base64 encoding
  debug:
    msg: "Hashicorp Vault secrets will be retrieved using base64 encoding: {{ _vault_secret_base64 }}"

- name: Get the secret id if the secret exists
  include_role:
    name: vault-has-secret

- name: Get secret value
  block:
    - name: Get the secret value
      shell: |
        vault kv get \
          -address={{ hashicorp_vault_address }} \ 
          -field={{ hashicorp_secret_field }} \
          {{ hashicorp_secret_name_path }}
      register: hashicorp_vault_get_secret_result

    - set_fact:
        secret_value: "{{ hashicorp_vault_get_secret_result.stdout | b64decode }}"
      when: _vault_secret_base64

    - set_fact:
        secret_value: "{{ hashicorp_vault_get_secret_result.stdout }}"
      when: not _vault_secret_base64
  when: 
    - has_secret == true
    - (hashicorp_secret_file | default("") == "")

- block:
  - name: Get secret value to file in plain text
    shell: |
      vault kv get \
        -address={{ hashicorp_vault_address }} \ 
        -field={{ hashicorp_secret_field }} \
        {{ hashicorp_secret_name_path }} > {{ hashicorp_secret_file }}
    register: hashicorp_vault_get_secret_result
    when: 
      - not _vault_secret_base64

  - block:
    - name: Get the base64 secret to file
      block: 
      - name: Create temporary file for base64 content
        tempfile:
          state: file
        register: _vault_secret_base64_file
      - name: Write base64 secret to temporary file
        shell: |
          vault kv get \
            -address={{ hashicorp_vault_address }} \ 
            -field={{ hashicorp_secret_field }} \
            {{ hashicorp_secret_name_path }} > {{ _vault_secret_base64_file.path }}
        register: hashicorp_vault_get_secret_result
      - name: Write secret to specified output file
        shell: |
          cat {{ _vault_secret_base64_file.path }} | base64 -d > {{ hashicorp_secret_file }}
    when: 
      - _vault_secret_base64

  - set_fact:
      secret_value: "{{ lookup('file', hashicorp_secret_file) }}"

  when: 
    - has_secret == true
    - (hashicorp_secret_file | default("") != "")

- set_fact:
    secret_value: ""
  when: has_secret == false