---
- name: Validate mandatory variables are defined for Get Secret
  assert:
    that:
      - _p_vault_secrets is defined or secret_name is defined
      - secret_group is defined

- name: Get secrets
  include_tasks: get-secrets.yml
  vars:
    secret_name: "{{ item.key }}"
    _p_secret_value: "{{ item.value }}"
  with_dict: "{{ _p_vault_secrets }}"
  when: _p_vault_secrets is defined

- include_tasks: get-secret.yml
  when: _p_vault_secrets is not defined