---
- name: Show secret {{ secret_group }}/{{ secret_name }}
  debug:
    var: secret_value
  vars:
    ansible_callback_diy_runner_on_ok_msg: |+2
      {{ secret_name }}: {{ ansible_callback_diy.result.output.secret_value }}
