---
- when: secret_value != ''
  block:
    - name: Create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tempfile_secret

    - name: Create file with secret
      copy:
        content: "{{ _secret_value_b64 | b64decode }}"
        dest: "{{ tempfile_secret.path }}"
        force: yes

    - name: Write secret to file {{ secret_file }} if one was specified
      shell: |
        cp -f {{ tempfile_secret.path }} {{ secret_file }}

    - name: Delete the temporary file
      file:
        path: "{{ tempfile_secret.path }}"
        state: absent
      when: tempfile_secret.path is defined

- name: Write empty value to file {{ secret_file }} if secret was not found
  shell: |
    echo "" > "{{ secret_file }}"
  when: secret_value == ''

